### PR TITLE
Add glue for pouchdb-find methods: query, createIndex, deleteIndex, and getIndexes.

### PR DESCRIPTION
**Pull request by brandonaaron**
Just started experimenting with ember-pouch and had a need for the query functionality... So I thought I'd  take a quick first pass at getting pouchdb-find methods integrated into this project (as described in #3 and [#7 on ember-pouch](https://github.com/nolanlawson/ember-pouch/issues/7)). I haven't tested this extensively beyond the few unit tests I added and any feedback is welcomed.

### CODE REVIEW

**Comment by brandonaaron** [comment]
Looks like the travis-ci build failed because of `Error: Cannot find module 'pouchdb'`. I experienced this locally when I first setup the project as well. Had to run `npm install pouchdb` to get up and running locally.

**Comment by nolanlawson** [comment]
Thanks for this PR, looks great! :) The issue with pouchdb is because the pouchdb module structure changed, so that `"pouchdb": "pouchdb/pouchdb"` in the package.json will no longer work. Instead, it should just use the latest version from npm.

I will give this a closer look, but it seems to be going in the right direction, and if the tests pass I'll be +1.

**Comment by nolanlawson** [comment]
I'm sorry for taking so long to get around to this. I'm taking a second look at it.

**Comment by nolanlawson** [comment]
closing in favor of #49

**Pull request closed without merging**
