### PR TITLE
Add SaveAll function.

### PR DESCRIPTION
**Pull request by ronyrun**
I tried to imlement it properly.

### CODE REVIEW

**Comment by nolanlawson** [comment]
Sorry, but there are a few mistakes here:

1) you modified the `dist` file, which is supposed to be written during `npm run build`
2) you added no tests

It also looks like you forgot to export the `saveAll` function and also there are some dangling `console.log` statements which I would prefer to remove. Please add some tests to describe your functionality and I'm sure you'll quickly discover how to fix these issues. Also note that Travis will complain if you don't have perfect code coverage, which you can test using `npm run coverage` (the reason it's green here is because you modified the `dist` files, which Travis doesn't check at all).

**Comment by ronyrun** [comment]
Sorry Nolan, that was my first try :)

**Comment by nolanlawson** [comment]
closing unless you want to give it another go :)

**Comment by ronyrun** [comment]
I updated it.
Let's try another GO :)

**Comment by nolanlawson** [comment]
It will still fail because there are no tests...

**Pull request closed without merging**
