### PR TITLE
Moar attachment tests

### PR DESCRIPTION
**Pull request by stevebest**
As advertised in #27: a test to see we don't lose an attachment on doc update, and another one to see we do lose it if we actually want it.

### CODE REVIEW

**Comment by nolanlawson** [comment]
Awesome, thank you!! Feeling way more confident about #27 now. :) Gonna publish a patch to npm/bower after merging.

**Comment by nolanlawson** [comment]
7de2866d1e280d5798a65a6e4300ac6a591094c1

**Comment by nolanlawson** [comment]
1.3.2 is published :)

**Comment by stevebest** [comment]
Supah cool, thanks!

**Pull request closed without merging**
