### PR TITLE
Fix relations fetches

### PR DESCRIPTION
**Pull request by akofman**
In case of many-to-many relations, fetches objects seem to be overridden.

I didn't manage to launch tests (I guess I have to install CouchDB) but if you add this one, I think that should reproduce the case ( if not I will install CouchDB I promise ;) ) : 

```
it('does many-to-many with several entities', function () {
      db.setSchema([
        {
          singular: 'author',
          plural: 'authors',
          relations: {
            'books': {hasMany: 'book'}
          }
        },
        {
          singular: 'book',
          plural: 'books',
          relations: {
            'authors': {hasMany: 'author'}
          }
        }
      ]);

      return db.rel.save('author', {
        name: 'Stephen King',
        id: 19,
        books: [1, 2]
      }).then(function () {
          return db.rel.save('author', {
            name: 'Peter Straub',
            id: 2,
            books: [3]
          });
        }).then(function () {
          return db.rel.save('book', {
            title: 'It',
            id: 1,
            authors: [19]
          });
        }).then(function () {
          return db.rel.save('book', {
            title: 'The Talisman',
            id: 2,
            authors: [19]
          });
        }).then(function () {
          return db.rel.save('book', {
            title: 'Ghost Story',
            id: 3,
            authors: [2]
          });
        }).then(function () {
          return db.rel.find('author');
        }).then(function (res) {
          ['authors', 'books'].forEach(function (type) {
            res[type].forEach(function (obj) {
              obj.rev.should.be.a('string');
              delete obj.rev;
            });
          });
          res.should.deep.equal({
            "authors": [
              {
                "name": "Peter Straub",
                "books": [
                  2,
                  3
                ],
                "id": 2
              },
              {
                "name": "Stephen King",
                "books": [
                  1,
                  2
                ],
                "id": 19
              }
            ],
            "books": [
              {
                "title": "It",
                "authors": [
                  19
                ],
                "id": 1
              },
              {
                "title": "The Talisman",
                "authors": [
                  19,
                  2
                ],
                "id": 2
              },
              {
                "title": "Ghost Story",
                "authors": [
                  2
                ],
                "id": 3
              }
            ]
          });
        });
    });
```

### CODE REVIEW

**Comment by akofman** [comment]
FYI, in this test I just removed a book in the array of Peter Straub's books.

**Comment by nolanlawson** [comment]
You don't need to install CouchDB; you can also `npm i -g pouchdb-server && pouchdb-server`. As for this PR, it seems to be failing due to coverage and Firefox; I'm trying to fix Firefox in #51.

**Comment by nolanlawson** [comment]
Sorry, can you rebase on master to test again? Had to change the config to fix a bunch of stuff.

**Comment by akofman** [comment]
Rebased ! And it's perfect with pouchdb-server, thanks.

Actually the issue was a little bit more tricky that what I expected ... so I also updated my commit and added a test.

When trying to find all authors from the plural like : `db.find('authors')`, the foundObjects array here : https://github.com/nolanlawson/relational-pouch/blob/master/lib/index.js#L342 contains two arrays. The "authors" one and the "author" which represents the fetched relations : 

authors (all authors)  => book (related books) => author (related authors from the related books).

Here: https://github.com/nolanlawson/relational-pouch/blob/master/lib/index.js#L346, the first array is overridden and if this one was different from the second one, the expected result becomes wrong. Let's assume we have an author without any books, he won't appear in the "author" array.

To fix that I just forced the singular from the find method in order to prevent multiple arrays for a same type in foundObjects.

Not sure it's clear, sorry for that ... I think the added test is a better explanation.

**Comment by nolanlawson** [comment]
Awesome, I can confirm that the test fails before your fix but succeeds after. The new test perfectly explains what the problem is.

I'll merge and push out a patch release right now. Thanks very much!

**Pull request merged**
